### ISSUE TITLE
coverage

### ISSUE THREAD

**Issue by lawremi** [sa-lee/plyranges#14]
Was looking at `set_coverage()`. What is the rationale for using the "set" verb there, since we are generating an entirely new set of ranges? Seems like it should be `compute_coverage()` or similar. Also, I think `compute_coverage()` or whatever we call it could just delegate to `coverage()` by default. Then, it calls some generic (maybe `as_ranges()`?) to generate a better data structure than an Rle or RleList. Rle would map to an IRanges, RleList to GRanges. This design lets us automatically support other `coverage()` methods, like BamFile and character (file path).

**Comment by sa-lee** [comment]
Agree that does seem a lot more sensible - will get around to refactoring today.
________________________________
