### ISSUE TITLE
`combine_ranges()`

### ISSUE THREAD

**Issue by lawremi** [sa-lee/plyranges#23]
It is not clear what this function does from the name. Is the "interweaving" of the left and right that useful in general? If we want to keep it, maybe `interweave()` is a better name? Or maybe the tidyverse already has one...

Is there a tidyverse verb that concatenates two or more objects while somehow adding a column indicating their origin?

I could imagine simplifying the last example in the README with
```
interweave(left=left, right=right)
```
It adds a column indicating the origin as either "left" or "right". That resembles the `mstack()` function in IRanges. It's not perfect, in part because it creates the origin column (what do we even call it?) implicitly. The closest tidyverse analog might be
```
melt(list(left=left, right=right))
```
which also allows specifying the name of the distinguishing column.

Of course, in general we do not want to interweave, just combine. Maybe the general verb would be `combine_groups()` or similar?

**Comment by sa-lee** [comment]
So I think the purpose of this function was to be like a dplyr equivalent `bind_rows` which takes a list of data.frames and sticks them together by row and adds an identifier column. I think that would be more useful to have that functionality as `combine_groups` than have the particular case for two ranges.

**Comment by lawremi** [comment]
So I guess that means `combine_groups()` should be called `bind_ranges()`. But there are a couple of different things going on,

1. How the ranges are combined; concatenation or interweaving? I would assume `bind_rows()` would concatenate. Or does it interweave? We should probably have two separate verbs for that.
2. Whether to add an identifying column. I'm surprised that `bind_rows()` does that by default, since I thought dplyr was trying to be highly cohesive and only do one thing at a time. But we should probably just follow its precedent and always add the column.

**Comment by sa-lee** [comment]
Ok so `bind_rows` in dplyr has an optional argument called .id = NULL which adds an identifying column - I guess we could port that to `bind_ranges`. So we'll have `bind_ranges` for concatenation and `interweave` for the special case of putting two ranges objects together.
