### ISSUE TITLE
R>3.5.0 requirements

### ISSUE THREAD

**Issue by mschubert** [sa-lee/plyranges#25]
Hi,

Your DESCRIPTION file specifies that R>3.5.0 is required which has not been released yet. This makes your Github `HEAD` not installable with the current R release (which is, I guess, roughly 100% of your users).

I found a warning on the [Bioconductor build process](http://bioconductor.org/spb_reports/plyranges_buildreport_20180307215752.html), which I think is the reason why you changed it, or is there any other reason as well?

If not, you might want to have a separate branch for the Bioconductor submission for now so that people can actually use your package with the current stable R.

**Comment by sa-lee** [comment]
Hi Michael,

Yes I'm trying to get this package on the next release of Bioconductor which is why I modified the description file on master but you're right I should have a way of letting people use it on the current R release (unfortunately the Bioconductor submission process needs to happen on master). I've created a new branch https://github.com/sa-lee/plyranges/tree/current-r-release until then.

Thanks for the suggestion!

**Comment by lawremi** [comment]
I've never really understood why they require a dependency on the current version of R. We should trust package authors to get that right.

It's enouraging that people are already interested in the package!

**Comment by mschubert** [comment]
It's not even the current version, but rather the version in active development.

There's some discussion on the [Bioc-devel mailing list](https://stat.ethz.ch/pipermail/bioc-devel/2018-February/012830.html) and we just had [a long thread on Twitter](https://twitter.com/_ms03/status/972440445665103872).

Bottom line: [Bioc-devel thinks this will make pkg developers download R-devel, Bioc-devel, and check their package against these](https://twitter.com/Bioconductor/status/972579321197023232).

Of course, this will break all packages currently being submitted to Bioconductor for use with the current stable version of R, leaving individual package developers to find a workaround for this mess (until the next Bioc release).

Quite frankly, I think it would be better to rely on automated tests and not abuse a package field in a way that was not intended (the R dependency should indicate minimum version for the package to function, not a convenience for Bioc developers).

**Comment by lawremi** [comment]
Agreed. Actually, BiocInstaller already enforces the correct R version.
