### ISSUE TITLE
Aware of valr?

### ISSUE THREAD

**Issue by PeteHaitch** [sa-lee/plyranges#29]
Stumbled across this (never used it)

https://f1000research.com/articles/6-1025/v1 
http://valr.hesselberthlab.org/

**Comment by lawremi** [comment]
Thanks, that's a relevant citation. It's a shame that they don't integrate with Bioconductor very well, and that all of their functions are prefixed with `bed_` for no reason. Reminds me of HelloRanges.

**Comment by sa-lee** [comment]
Hi Pete, thanks for the link - we should cite it in our manuscript
