### ISSUE TITLE
Implement gather/spread and unite/extract from tidyr

### ISSUE THREAD

**Issue by sa-lee** [sa-lee/plyranges#39]
Related to #16  (the last check box)

I feel like these names in tidyr are confusing - perhaps we should rename them?

`gather` takes a data.frame from wide to long (gathers columns into a key value pairs)

https://tidyr.tidyverse.org/reference/gather.html
For a GRanges object this should only be able to performed on the metadata and not touch the core GRanges. But what about the case of having a GAlignmentPairs or DataFrame with GRanges columns? There should be another verb maybe `gather_as_granges` or something similar?

For the formal arguments of gather I don't think anything after the ... is relevant, ideally the key should be an RLE column - which does suggest we use a new verb?

`spread` is the inverse of gather
https://tidyr.tidyverse.org/reference/spread.html
This has the ability to modify the type of an input GRanges - again suggesting a new verb?

`unite`/ `extract` combine multiple columns into one or takes one column and splits them to many.
It is probably a useful helper function given how sample names are usually compositional.
https://tidyr.tidyverse.org/reference/unite.html

**Comment by lawremi** [comment]
Not sure we should worry about this right now. Use cases for these operations will often arise in multi-sample cases, where one is using a SummarizedExperiment anyway. Maybe we should focus on that first?

**Comment by sa-lee** [comment]
I agree - was just flagging it for the GAlignmentPairs and two GRanges columns in a DataFrame case
