### ISSUE TITLE
Unexpected behaviour with stretching w/o anchor

### ISSUE THREAD

**Issue by mschubert** [sa-lee/plyranges#49]
Hi,

I'm trying to `stretch` a genomic region using different anchoring. I also tried without anchoring, which yielded the (unexpected) result below:

```r
> x = makeGRangesFromDataFrame(data.frame(
    seqnames=1:2, start=c(10,100), end=c(200,300), strand=c('+','-')))

> x
      seqnames     ranges strand
         <Rle>  <IRanges>  <Rle>
  [1]        1    10-200      +
  [2]        2   100-300      -

> stretch(x, 2)
      seqnames     ranges strand
         <Rle>  <IRanges>  <Rle>
  [1]        1   104-106      +
  [2]        2   199-201      -
```

Why does it change the regions this way? (anchored stretching works as expected)

Using `IRanges_2.14.10` and `plyranges_1.0.3` (current Bioconductor release).

**Comment by sa-lee** [comment]
It looks like the default is to stretch out from the centre, , which is not what my documentation says, so this is at least unexpected in that regard. 

What output would expect here? Stretching by 2 away from the start and end?

```r
> x %>% mutate(start = start - 2L, end = end + 2L)
GRanges object with 2 ranges and 0 metadata columns:
      seqnames    ranges strand
         <Rle> <IRanges>  <Rle>
  [1]        1     8-202      +
  [2]        2    98-302      -
  -------
  seqinfo: 2 sequences from an unspecified genome; no seqlengths
```

**Comment by lawremi** [comment]
Probably should behave however the `start<-()`, `end()<-` etc setters behave now.

**Comment by sa-lee** [comment]
`mutate` uses those setters behind the scenes so the behaviour should be consistent.

**Comment by sa-lee** [comment]
wondering if we could refactor here to have stretch just work inside `mutate` like we have been discussing in #47

**Comment by mschubert** [comment]
@sa-lee I would expect `stretch(., 0)` to be a no-op, positive numbers to increase the overall range and negative to decrease overall range.

Personally, I wouldn't mind an error (or warning + default anchor) if the interval is not anchored.

**Comment by lawremi** [comment]
Agreed, I would have expected `stretch_center()` (the internal function corresponding to this case) to be like the `+,Ranges()` in IRanges: it would add half the amount to each end.

**Comment by mschubert** [comment]
Note that this also happens for:

```r
> stretch(anchor_center(x), 2)
      seqnames     ranges strand
         <Rle>  <IRanges>  <Rle>
  [1]        1   104-106      +
  [2]        2   199-201      -
```

(start, end, 5p, 3p anchors work as expected)

**Comment by sa-lee** [comment]
Okey I'll change the default/centering to be like `+, Ranges` for now. I am also leaning towards your suggestion of having stretch throw a warning for no anchoring.

**Comment by mschubert** [comment]
I didn't realize at before, but I'm also confused about `anchor_end`:

```r
> stretch(anchor_end(x), 2)
      seqnames     ranges strand
         <Rle>  <IRanges>  <Rle>
  [1]        1    12-200      +
  [2]        2   102-300      -
```

This seems to shorten rather than stretch?

**Comment by sa-lee** [comment]
Yep that looks wrong to me too. It should go the the other way.

**Comment by mschubert** [comment]
:tada:
