### ISSUE TITLE
plyranges::filter not working with <CharacterList> objects

### ISSUE THREAD

**Issue by annaquaglieri16** [sa-lee/plyranges#58]
Hey Stuart, 

I would like to subset a TxDb object by gene_id. However, the plyranges::filter function does not work at the moment with `CharacterList` objects. 

```
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(plyranges)

exons(TxDb.Hsapiens.UCSC.hg38.knownGene,columns=c("gene_id","exon_rank"))
```

```
GRanges object with 6 ranges and 2 metadata columns:
      seqnames      ranges strand |         gene_id
         <Rle>   <IRanges>  <Rle> | <CharacterList>
  [1]     chr1 29554-30039      + |            <NA>
  [2]     chr1 30267-30667      + |            <NA>
  [3]     chr1 30366-30503      + |       100302278
  [4]     chr1 30564-30667      + |            <NA>
  [5]     chr1 30976-31097      + |            <NA>
  [6]     chr1 30976-31109      + |            <NA>
          exon_rank
      <IntegerList>
  [1]             1
  [2]             1
  [3]             1
  [4]             2
  [5]             3
  [6]             2
  -------
  seqinfo: 455 sequences (1 circular) from hg38 genome
```

```
exon <- exons(TxDb.Hsapiens.UCSC.hg38.knownGene,columns=c("gene_id","exon_rank")) %>%
  plyranges::filter(gene_id %in% "2322")
```

```
Error in getListElement(x, i, ...) : 
  GRanges objects don't support [[, as.list(), lapply(),
  or unlist() at the moment
```

Cheers, 

Anna

**Comment by sa-lee** [comment]
Hi Anna,

I don't necessarily think this is a bug on plyranges part - but would like to hear if @lawremi has any opinions. The equivalent Bioconductor code throws the same error
```{r}
gr <- exons(TxDb.Hsapiens.UCSC.hg38.knownGene,columns=c("gene_id","exon_rank"))
gr[gr$gene_id %in% "2322", ]
Error in getListElement(x, i, ...) : 
  GRanges objects don't support [[, as.list(), lapply(), or unlist() at the moment 
```

Considering you could have multiple genes that have an associated exon, the use of `%in%` here on a `CharacterList` returns a `LogicalList` so it's not clear how to filter if an entry has multiple TRUE/FALSE entries. To require at least one gene_id with value "2322" you could use

```{r}
exons(TxDb.Hsapiens.UCSC.hg38.knownGene,columns=c("gene_id","exon_rank")) %>%
  plyranges::filter(any(gene_id %in% "2322"))
```

Perhaps a more plyranges approach would be to unnest the CharacterList column first,
then the filter will work as is.

```{r}
exons(TxDb.Hsapiens.UCSC.hg38.knownGene,columns=c("gene_id","exon_rank")) %>%
  plyranges::unnest(gene_id) %>%
  plyranges::filter(gene_id %in% "2322")
```

**Comment by lawremi** [comment]
These solutions make sense. We might want a way for the user to assert that a CharacterList only contains empty (unnested to `NA`) or length-one elements, so that they can ensure that the structure of the data does not change when unnesting. There is a methond on `drop()` that currently does this on Lists.

**Comment by annaquaglieri16** [comment]
Thanks Stuart!

I think I was missing the knowledge of the `unnest` function, I was trying to `unlist` but your solution works neatly and does what I needed. 

Anna

**Comment by sa-lee** [comment]
No problem @annaquaglieri16!

@lawremi makes sense - I don't think that's currently supported.

**Comment by lawremi** [comment]
So no plans to add that constraint checking feature?

**Comment by sa-lee** [comment]
of course but there’s for a new issue 😀
