### ISSUE TITLE
Vignette's titles links redirect to 404 - Page not found

### ISSUE THREAD

**Issue by annaquaglieri16** [sa-lee/plyranges#59]
Hi Stuart, 

This might be just some problem with hosting the Plyranges website, but when I am on this page https://sa-lee.github.io/plyranges/articles/common-tasks.html and I click on one of the header sections on the right to go into a different section, I get redirected to a 404 - Page not found page. 

Cheers, 
Anna

**Comment by sa-lee** [comment]
I see what you mean the top level headers work but if you click on the function it tries to go that function's help page which throws the 404. I think this might be a pkgdown thing that I need to fix. Thanks for the note.

**Comment by sa-lee** [comment]
(ps if you want to help with the docs or think anything needs clarification, you are more than welcome to contribute)

**Comment by annaquaglieri16** [comment]
Thanks Stuart!

Anna

**Comment by sa-lee** [comment]
I've now moved the extended vignette to [sa-lee/plyrangesWorkshops](https://github.com/sa-lee/plyrangesWorkshops).
