### ISSUE TITLE
An `mtcars` or `diamonds` dataset for plyranges

### ISSUE THREAD

**Issue by sa-lee** [sa-lee/plyranges#7]
I feel like this is something `ggplot` and `dplyr` do quite well in that they provide concrete examples via a simple dataset. I think this makes things simpler to learn and gives intuition about how the API works. 

Is there anything equivalent we could use for plyranges?

**Comment by lawremi** [comment]
Not really. The problem is that genomic data are complex, and there are many types of genomic datasets. There is no basic, generic one. Bioconductor does provide a variety of datasets and annotations for reuse though. Looking at the workflows on the Bioc website might be a good place to start.

**Comment by sa-lee** [comment]
Ok that's true. some of the datasets in the `HelloRangesData` package are probably useful for this purpose. Perhaps it's better to use  toy examples in the introduction vignette and have more specialised examples in _case-study_ vignettes.
