### ISSUE TITLE
left joins fail on granges if right has no mcols and some left ranges do not overlap

### ISSUE THREAD

**Issue by ripkrizbi** [sa-lee/plyranges#70]
Hi, here is a quick example to demonstrate:

```
# gr0 has ranges on chr5 while gr1 doesn't
gr0 <- GRanges(Rle(c("chr2", "chr5", "chr1", "chr3"), c(1, 3, 2, 4)),
                IRanges(1:10, width=10:1))

gr1 <- GRanges(Rle(c("chr2", "chr3", "chr1", "chr3"), c(1, 3, 2, 4)),
                IRanges(1:10, width=10:1))

# left join fails
gr0 %>% join_overlap_left(gr1)

## Error in DataFrame(..., check.names = FALSE) : 
##   different row counts implied by arguments

# add some mcols to rhs
gr1$AAA <- 1

# and it starts to work :)
gr0 %>% join_overlap_left(gr1)

## GRanges object with 36 ranges and 1 metadata column:
##        seqnames    ranges strand |       AAA
##           <Rle> <IRanges>  <Rle> | <numeric>
##    [1]     chr2      1-10      * |         1
##    [2]     chr5      2-10      * |      <NA>
##    [3]     chr5      3-10      * |      <NA>
##    [4]     chr5      4-10      * |      <NA>
##    [5]     chr1      5-10      * |         1
##    ...      ...       ...    ... .       ...
##   [32]     chr3        10      * |         1
##   [33]     chr3        10      * |         1
##   [34]     chr3        10      * |         1
##   [35]     chr3        10      * |         1
##   [36]     chr3        10      * |         1
##   -------
##   seqinfo: 5 sequences from an unspecified genome; no seqlengths

```

I have traced the issue down to the piece of code that tries to construct mcols for outer matches, but fails if there are no mcols to start with and instead of generating a DataFrame of the appropriate number of rows (and zero cols), it always seems to generate a 0,0 DataFrame, which then fails to merge with (another empty) mcols frame on the right. If there are some metadata in the right ranges, then all works without a glitch. 

https://github.com/sa-lee/plyranges/blob/da3c4f40292ac3a4cd0ad9c4b383ca9ab0a3db91/R/ranges-overlap-joins-outer.R#L44

**Comment by sa-lee** [comment]
Thanks for the report - will get around to this in the next week or so. In the meantime you are more then welcome to contribute a PR that fixes this issue :)

**Comment by sa-lee** [comment]
This should be fixed now. I've pushed the changes to both release and devel branches on Bioconductor.
