### ISSUE TITLE
vignettes as case studies

### ISSUE THREAD

**Issue by sa-lee** [sa-lee/plyranges#8]
I think the following would give sufficient coverage of the API 

- [ ] case study on the join grammar: overlap joins between differentially methylated regions and cpg islands. This could detail both joins and the arithmetic of resizing/anchoring.

- [ ] case study on aggregation:  summarising overlaps by some feature of interest, the grouping classes. one example would be average coverage over some genomic feature (`group_by_overlaps`)

**Comment by sa-lee** [comment]
for case study 1, look at the human epigenome roadmap data (available for bioconductor AnnotationHub) can use these read BigWig files and narrowPeak files and perform aggregation and find overlaps.

**Comment by sa-lee** [comment]
@dicook suggested removing the comparison API as not really of interest and means we can get rid of some packages in suggests.

**Comment by lawremi** [comment]
What is the comparison API?

**Comment by sa-lee** [comment]
Sorry typo - meant the vignette - basically where I was testing out how plyranges could be used like bedtools or HelloRanges

**Comment by lawremi** [comment]
Ok. Comparisons that would be relevant include:
1. To the original Ranges API (as suggested by Rob)
2. To plain dplyr operations (showing why high-level operations are useful)

**Comment by sa-lee** [comment]
I agree - I think they are in the intro vignette (I've included a table of mappings from plyranges to the original Ranges API)

**Comment by sa-lee** [comment]
At this point I'm fairly happy with the intro vignette, I still think redoing the bedtools vignette with plyranges is a valuable exercise but doesn't need to be included with the package and could be a stand alone document.  As for the other examples I think we could use the examples I've written up in the paper.

**Comment by lawremi** [comment]
Agreed
