### ISSUE TITLE
Question about usability

### ISSUE THREAD

**Issue by tonperre** [sa-lee/plyranges#87]
Hi,

I just wondered how to use Plyranges to combine two datasets (one with the peaks, one with the intervals I want to compute the peaks in) to get the average peak score per interval
I tried with join_overlap but I have the feeling that it makes duplicated regarding the strands ?

Best

**Comment by sa-lee** [comment]
If you want the overlaps to account for strand, use the `join_overlap_*_directed` family of functions.

**Comment by sa-lee** [comment]
Also we have an example of doing something similar to this in our fluentGenomics workflowhttps://bioconductor.org/packages/3.13/workflows/vignettes/fluentGenomics/inst/doc/fluentGenomics.html
