### ISSUE TITLE
Suggestion: Add figures of overlap operations to vignette

### ISSUE THREAD

**Issue by PeteHaitch** [sa-lee/plyranges#9]
Hey Stuart,

Looks like this is coming along nicely. A superficial suggestion and probably something you've thought of: perhaps you could add figures/cartoons to illustrate what's happening with overlap-based ops on `Ranges` (https://github.com/sa-lee/plyranges/blob/master/vignettes/introduction-plyranges.md#joins-or-another-way-at-looking-at-overlaps-between-ranges). I think that will help many users understand the output (I certainly struggle with just the R output).

The [**IRanges** vignette](http://bioconductor.org/packages/release/bioc/vignettes/IRanges/inst/doc/IRangesOverview.pdf) has some, but I was really thinking about the **bedtools** docs (e.g., http://bedtools.readthedocs.io/en/latest/content/tools/merge.html) which I found very helpful when reasoning about or teaching interval algebra. Oh, I just realised that **HelloRanges** uses some of the **bedtools** figs http://bioconductor.org/packages/release/bioc/vignettes/HelloRanges/inst/doc/tutorial.pdf ...

And if you happen to write a function that makes pretty pictures of `Ranges` and overlaps I'm sure that'd be useful for teaching purposes

**Comment by sa-lee** [comment]
That's a great suggestion, thanks Pete! I like the idea of making a plotting functions for the types of overlaps

**Comment by lawremi** [comment]
There are also diagrams from the IRanges paper: http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003118

And the Nature Methods paper: https://www.nature.com/articles/nmeth.3252
